group: Unet - Pitch Prediction
dataset:
    piano_only: True
    window_size: 8192
    sampling_rate: 11000
    batch_size: 5
    n_windows: 2
training:
    epochs: 50
    lr: 1.0e-3
    pos_weight: 10
    convert_rate: 5
    convert_seconds: 2
    positive_threshold: 0.9
model_params:
    kernel_size: 1024
    stride: 3
    n_filters: 50
    n_layers: 3
    model_type: Unet
